# Generated by Django 5.0.3 on 2024-03-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('item_group_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('unit_of_measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_of_measurement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('reorder_point', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufactured', models.BooleanField()),
                ('min_qty_for_manufacturing', models.PositiveIntegerField()),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemgroup')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement')),
            ],
        ),
    ]
