# Generated by Django 5.0.3 on 2024-03-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTerms',
            fields=[
                ('purchase_term_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_uom', models.CharField(max_length=50)),
                ('conversion_for_uom', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_vendor_uom', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_qty', models.PositiveIntegerField()),
                ('item_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.vendor')),
            ],
        ),
    ]
